create table battles(
	id serial not null,
	name varchar(255) not null,
	year varchar(255) null,
	battle_number varchar(255) null,
	attacker_king varchar(255) null,
	defender_king varchar(255) null,
	attacker_1 varchar(255) null,
	attacker_2 varchar(255) null,
	attacker_3 varchar(255) null,
	attacker_4 varchar(255) null,
	defender_1 varchar(255) null,
	defender_2 varchar(255) null,
	defender_3 varchar(255) null,
	defender_4 varchar(255) null,
	attacker_outcome varchar(255) not null,
	battle_type varchar(255) null,
	major_death varchar(255) null,
	major_capture varchar(255)null,
	attacker_size varchar(255) null,
	defender_size varchar(255) not null,
	attacker_commander varchar(255) null,
	defender_commander varchar(255) null,
	summer varchar(255) null,
	location varchar(255) null,
	region varchar(255) not null,
	note varchar(255) null,
	primary key (id)
);
